[tmifm_maily]
title = "차우진의 TMI.FM ─ 메일리"
url = "https://maily.so/draft.briefing"
entrySelector = "div[class='grid gap-2 lg:gap-4'] div[class='w-full h-auto flex flex-col flex border border-gray-200']"
titleSelector = "div[class='text-gray-900 font-bold text-base lg:text-xl whitespace-normal truncate-2-lines']"
linkSelector = "a"
contentSelector = "p[class='text-gray-700 text-sm lg:text-base truncate-2-lines']"
imageSelector = "div[class='flex-shrink-0 w-full h-20 lg:h-32 flex-none bg-cover text-center overflow-hidden']"
waitUntil = "networkidle"

[tmifm_naverpremiumcontents]
title = "TMI.FM 팬덤랩스 ─ 네이버 프리미엄콘텐츠"
url = "https://contents.premium.naver.com/tmifm/labs/contents"
entrySelector = "ul.content_list._CONTENT_LIST li.content_item.as_thumb"
titleSelector = "strong.content_title"
linkSelector = "a.content_text_link"
contentSelector = "a.content_category"
imageSelector = "a.content_thumb img"
waitUntil = "networkidle"

[tmifm_kakaotalk]
title = "TMI.FM 뮤직랩스 ─ 카카오톡 채널"
url = "https://pf.kakao.com/_nuEns"
entrySelector = "ul.list_news li"
titleSelector = "span.txt_g"
linkSelector = "a.link_item"
waitUntil = "networkidle"
